### ISSUE TITLE
Issue with latest release 1.0.1

### ISSUE THREAD

**Issue by tommarien** [ianschmitz/jest-environment-jsdom-fifteen#5]
Due to addition of resourceloader all tests now actually tries to load the resources, which we cannot seem to toggle off.

see https://github.com/jsdom/jsdom#loading-subresources

Please advise

**Comment by ianschmitz** [comment]
Ah yes thank you for reporting @tommarien. That was an unintended consequence of trying to fix `userAgent` support in #4. I'll revert and push out a patch shortly.

**Comment by ianschmitz** [comment]
Reverted in `1.0.2`. @diegohaz just a heads up that this reverted your change.

**Comment by tommarien** [comment]
@ianschmitz Thanks ;)

**Comment by diegohaz** [comment]
@ianschmitz Thanks for letting me know and taking care of this so fast! Posted an alternative solution for my problem here: https://github.com/ianschmitz/jest-environment-jsdom-fifteen/issues/3#issuecomment-559891156
